### ISSUE TITLE
Q&A about standard ipmitool 

### ISSUE THREAD

**Issue by bojahng** [dnslin/IPMIToolWin#1]
What is the difference between yours and https://github.com/ipmitool/ipmitool/

**Comment by dnslin** [comment]
this is a self-compiled copy of IPMITool for windows, which runs under win7, win10 and win11.

**Comment by bojahng** [comment]
The one compiled by myself cannot be used in windows2016, but it can be used with yours. I would like to know your configure options.
problem descriptions:
https://github.com/ipmitool/ipmitool/issues/397


my configure opctions:
./configure  --enable-intf-lanplus=yes --enable-intf-imb=yes IANADIR=.local/usr/share/misc

**Comment by dnslin** [comment]
It's been a long time. this repository is just a backup of what I had packed.

**Comment by jiruiwu** [comment]
Hi dnslin, do you remeber how you solved "Error: no IMB driver found at /dev/imb!"(maybe you didn't meet that)?
At same windows OS, I execute ipmitool that built from you and didn't happend "Error: no IMB driver found at /dev/imb!" but the ipmitool(v1.8.19) built from me occured this Error.

This is my build procedure.
```
$ ./bootstrap
$ ./configure --enable-intf-lanplus --enable-intf-imb DEFAULT_INTF="imb" IANADIR=assignments --prefix=/tmp/ipmitoolv1.8.19-win
$ LANG=C make
$ make install
$ mkdir ipmitoolv1.8.19-win_fix
$ cp -rp /tmp/ipmitoolv1.8.19-win_sol/share/doc/ipmitool ipmitoolv1.8.19-win_fix/doc
$ cp -rp assignments/ ipmitoolv1.8.19-win_fix/.
$ cp /bin/{cygwin1.dll,cygcrypto*,cygz.dll,cyggcc_s-*.dll,cygreadline*.dll,cygncursesw-*.dll} ipmitoolv1.8.19-win_fix/.
$ cp -rp src/.libs/ipmitool.exe ipmitoolv1.8.19-win_fix/.
```
